-- Corrected Demo Data for LotusHealth - LLM AI Agent Testing
-- This script populates the database with realistic medical data for testing

-- Clear existing data (optional - uncomment if you want to start fresh)
-- DELETE FROM appointments;
-- DELETE FROM schedules;
-- DELETE FROM doctors;
-- DELETE FROM patients;
-- DELETE FROM users;

-- Insert demo users (skip if already exist)
INSERT INTO users (username, email, password_hash, first_name, last_name, full_name, role, is_active) VALUES
('admin', 'admin@lotushealth.com', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/RK.s5u.Gi', 'Admin', 'User', 'Admin User', 'admin', true),
('dr.smith', 'dr.smith@lotushealth.com', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/RK.s5u.Gi', 'John', 'Smith', 'Dr. John Smith', 'doctor', true),
('dr.johnson', 'dr.johnson@lotushealth.com', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/RK.s5u.Gi', 'Sarah', 'Johnson', 'Dr. Sarah Johnson', 'doctor', true),
('dr.williams', 'dr.williams@lotushealth.com', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/RK.s5u.Gi', 'Michael', 'Williams', 'Dr. Michael Williams', 'doctor', true),
('nurse.brown', 'nurse.brown@lotushealth.com', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/RK.s5u.Gi', 'Emily', 'Brown', 'Emily Brown', 'nurse', true),
('receptionist.davis', 'receptionist.davis@lotushealth.com', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/RK.s5u.Gi', 'David', 'Davis', 'David Davis', 'receptionist', true)
ON CONFLICT (username) DO NOTHING;

-- Insert demo patients with realistic medical histories
INSERT INTO patients (user_id, first_name, last_name, date_of_birth, gender, phone, email, address, emergency_contact, medical_history, allergies, medications) VALUES
(NULL, 'Alice', 'Wilson', '1985-03-15', 'female', '+1-555-0101', 'alice.wilson@email.com', '123 Oak Street, Springfield, IL 62701', 'Bob Wilson (Husband) +1-555-0102', 'Hypertension diagnosed 2018, Type 2 Diabetes diagnosed 2020, Previous appendectomy 2015', ARRAY['Penicillin', 'Sulfa drugs'], ARRAY['Metformin 500mg twice daily', 'Lisinopril 10mg daily', 'Atorvastatin 20mg daily']),
(NULL, 'Robert', 'Chen', '1972-07-22', 'male', '+1-555-0202', 'robert.chen@email.com', '456 Maple Avenue, Chicago, IL 60601', 'Lisa Chen (Wife) +1-555-0203', 'Asthma since childhood, GERD diagnosed 2019, Previous knee surgery 2017', ARRAY['Aspirin', 'Ibuprofen'], ARRAY['Albuterol inhaler as needed', 'Omeprazole 40mg daily', 'Montelukast 10mg daily']),
(NULL, 'Maria', 'Garcia', '1990-11-08', 'female', '+1-555-0303', 'maria.garcia@email.com', '789 Pine Road, Milwaukee, WI 53201', 'Carlos Garcia (Brother) +1-555-0304', 'Depression diagnosed 2018, Migraines since adolescence, No major surgeries', ARRAY['Codeine', 'Morphine'], ARRAY['Sertraline 100mg daily', 'Sumatriptan 50mg as needed', 'Multivitamin daily']),
(NULL, 'James', 'Taylor', '1965-12-03', 'male', '+1-555-0404', 'james.taylor@email.com', '321 Elm Street, Detroit, MI 48201', 'Patricia Taylor (Wife) +1-555-0405', 'Coronary artery disease diagnosed 2018, Previous heart attack 2019, Hypertension', ARRAY['Shellfish', 'Peanuts'], ARRAY['Metoprolol 50mg twice daily', 'Aspirin 81mg daily', 'Atorvastatin 40mg daily', 'Lisinopril 20mg daily']),
(NULL, 'Jennifer', 'Anderson', '1988-05-17', 'female', '+1-555-0505', 'jennifer.anderson@email.com', '654 Birch Lane, Minneapolis, MN 55401', 'Mark Anderson (Husband) +1-555-0506', 'Hypothyroidism diagnosed 2015, PCOS diagnosed 2016, Previous C-section 2020', ARRAY['Latex', 'Dairy'], ARRAY['Levothyroxine 75mcg daily', 'Metformin 1000mg twice daily', 'Prenatal vitamin daily']),
(NULL, 'Thomas', 'Martinez', '1978-09-25', 'male', '+1-555-0606', 'thomas.martinez@email.com', '987 Cedar Court, Denver, CO 80201', 'Sofia Martinez (Wife) +1-555-0607', 'Sleep apnea diagnosed 2017, Obesity, Previous gallbladder removal 2019', ARRAY['None known'], ARRAY['CPAP therapy nightly', 'Vitamin D 2000 IU daily', 'Fish oil 1000mg daily']),
(NULL, 'Lisa', 'Thompson', '1982-01-30', 'female', '+1-555-0707', 'lisa.thompson@email.com', '147 Willow Way, Seattle, WA 98101', 'Kevin Thompson (Husband) +1-555-0708', 'Fibromyalgia diagnosed 2019, Chronic fatigue syndrome, Previous hysterectomy 2020', ARRAY['Sulfa drugs', 'Tetracycline'], ARRAY['Gabapentin 300mg three times daily', 'Duloxetine 60mg daily', 'Melatonin 5mg nightly']),
(NULL, 'Christopher', 'Lee', '1975-04-12', 'male', '+1-555-0808', 'christopher.lee@email.com', '258 Spruce Street, Portland, OR 97201', 'Amanda Lee (Wife) +1-555-0809', 'Rheumatoid arthritis diagnosed 2016, Osteoporosis diagnosed 2018, Previous hip replacement 2019', ARRAY['Sulfa drugs'], ARRAY['Methotrexate 15mg weekly', 'Folic acid 5mg daily', 'Calcium carbonate 600mg twice daily', 'Vitamin D3 1000 IU daily'])
ON CONFLICT (email) DO NOTHING;

-- Insert demo doctors (skip if already exist)
INSERT INTO doctors (user_id, specialization, license_number, years_experience, education, certifications, is_active) VALUES
((SELECT id FROM users WHERE username = 'dr.smith'), 'Cardiology', 'IL-CARD-001234', 15, ARRAY['MD - Harvard Medical School', 'Residency - Johns Hopkins Hospital', 'Fellowship - Mayo Clinic'], ARRAY['Board Certified in Cardiology', 'Fellow of American College of Cardiology', 'ACLS Certified'], true),
((SELECT id FROM users WHERE username = 'dr.johnson'), 'Dermatology', 'IL-DERM-005678', 12, ARRAY['MD - Stanford Medical School', 'Residency - UCLA Medical Center', 'Fellowship - NYU Langone'], ARRAY['Board Certified in Dermatology', 'Fellow of American Academy of Dermatology', 'Mohs Surgery Certified'], true),
((SELECT id FROM users WHERE username = 'dr.williams'), 'Neurology', 'IL-NEUR-009012', 18, ARRAY['MD - Yale Medical School', 'Residency - Massachusetts General Hospital', 'Fellowship - Cleveland Clinic'], ARRAY['Board Certified in Neurology', 'Fellow of American Academy of Neurology', 'Epilepsy Specialist'], true)
ON CONFLICT (license_number) DO NOTHING;

-- Insert demo appointments
INSERT INTO appointments (patient_id, doctor_id, appointment_type, status, scheduled_date, duration_minutes, notes) VALUES
((SELECT id FROM patients WHERE email = 'alice.wilson@email.com'), (SELECT id FROM doctors WHERE license_number = 'IL-CARD-001234'), 'follow_up', 'confirmed', '2024-09-15 10:00:00', 30, 'Follow-up for hypertension management. Patient reports occasional dizziness. BP readings at home: 140/90 average.'),
((SELECT id FROM patients WHERE email = 'robert.chen@email.com'), (SELECT id FROM doctors WHERE license_number = 'IL-DERM-005678'), 'consultation', 'scheduled', '2024-09-16 14:30:00', 45, 'New patient consultation for persistent rash on arms and chest. Rash has been present for 3 weeks, mildly pruritic.'),
((SELECT id FROM patients WHERE email = 'maria.garcia@email.com'), (SELECT id FROM doctors WHERE license_number = 'IL-NEUR-009012'), 'office_visit', 'scheduled', '2024-09-17 09:15:00', 60, 'Patient reports increased frequency of migraines. Current medication not providing adequate relief. Last migraine was 2 days ago, lasted 8 hours.'),
((SELECT id FROM patients WHERE email = 'james.taylor@email.com'), (SELECT id FROM doctors WHERE license_number = 'IL-CARD-001234'), 'routine_checkup', 'confirmed', '2024-09-18 11:00:00', 45, 'Annual cardiac checkup. Patient reports good medication compliance. No new symptoms.'),
((SELECT id FROM patients WHERE email = 'jennifer.anderson@email.com'), (SELECT id FROM doctors WHERE license_number = 'IL-DERM-005678'), 'follow_up', 'scheduled', '2024-09-19 15:45:00', 30, 'Follow-up for acne treatment. Patient reports improvement but still experiencing breakouts.'),
((SELECT id FROM patients WHERE email = 'thomas.martinez@email.com'), (SELECT id FROM doctors WHERE license_number = 'IL-NEUR-009012'), 'consultation', 'scheduled', '2024-09-20 13:00:00', 60, 'New patient with sleep issues. Reports difficulty falling asleep and frequent awakenings. CPAP compliance is poor.'),
((SELECT id FROM patients WHERE email = 'lisa.thompson@email.com'), (SELECT id FROM doctors WHERE license_number = 'IL-CARD-001234'), 'emergency', 'in_progress', '2024-09-14 16:30:00', 90, 'Patient presents with chest pain and shortness of breath. EKG shows ST elevation. Immediate intervention required.'),
((SELECT id FROM patients WHERE email = 'christopher.lee@email.com'), (SELECT id FROM doctors WHERE license_number = 'IL-DERM-005678'), 'office_visit', 'completed', '2024-09-13 10:30:00', 45, 'Routine skin check. No suspicious lesions found. Patient reports good medication compliance for RA.')
ON CONFLICT DO NOTHING;

-- Insert demo schedules
INSERT INTO schedules (doctor_id, date, start_time, end_time, is_available, notes) VALUES
((SELECT id FROM doctors WHERE license_number = 'IL-CARD-001234'), '2024-09-15', '09:00:00', '17:00:00', true, 'Regular clinic hours'),
((SELECT id FROM doctors WHERE license_number = 'IL-CARD-001234'), '2024-09-16', '09:00:00', '17:00:00', true, 'Regular clinic hours'),
((SELECT id FROM doctors WHERE license_number = 'IL-DERM-005678'), '2024-09-15', '08:00:00', '16:00:00', true, 'Regular clinic hours'),
((SELECT id FROM doctors WHERE license_number = 'IL-DERM-005678'), '2024-09-16', '08:00:00', '16:00:00', true, 'Regular clinic hours'),
((SELECT id FROM doctors WHERE license_number = 'IL-NEUR-009012'), '2024-09-15', '10:00:00', '18:00:00', true, 'Regular clinic hours'),
((SELECT id FROM doctors WHERE license_number = 'IL-NEUR-009012'), '2024-09-16', '10:00:00', '18:00:00', true, 'Regular clinic hours')
ON CONFLICT DO NOTHING;

-- Insert demo knowledge base for AI agent testing
INSERT INTO knowledge_base (category, title, content, source, version, keywords, related_topics) VALUES
('Cardiology', 'Hypertension Management Guidelines', 'Hypertension is defined as blood pressure ≥130/80 mmHg. First-line treatment includes lifestyle modifications: sodium restriction (<2.3g/day), DASH diet, regular exercise, weight loss, and smoking cessation. Pharmacological treatment should be initiated for BP ≥140/90 mmHg in most patients. First-line medications include ACE inhibitors, ARBs, CCBs, and thiazide diuretics. Regular monitoring every 3-6 months is recommended.', 'American Heart Association Guidelines 2023', '1.0', ARRAY['hypertension', 'blood pressure', 'cardiovascular', 'treatment', 'guidelines'], ARRAY['lifestyle modifications', 'pharmacotherapy', 'monitoring', 'risk factors']),
('Dermatology', 'Acne Vulgaris Treatment', 'Acne vulgaris is a common inflammatory skin condition affecting 85% of adolescents. Treatment depends on severity: mild (topical retinoids, benzoyl peroxide), moderate (topical antibiotics + retinoids), severe (oral antibiotics, isotretinoin). Patient education on proper skin care, avoiding picking, and sun protection is crucial. Treatment duration is typically 8-12 weeks with gradual improvement.', 'American Academy of Dermatology Guidelines 2023', '1.0', ARRAY['acne', 'dermatology', 'treatment', 'skin care', 'retinoids'], ARRAY['topical therapy', 'oral therapy', 'patient education', 'prevention']),
('Neurology', 'Migraine Management', 'Migraines are recurrent headaches lasting 4-72 hours with characteristic features: unilateral location, pulsating quality, moderate-severe intensity, and aggravation by routine activity. Acute treatment includes NSAIDs, triptans, and antiemetics. Preventive treatment is indicated for ≥4 attacks/month and includes beta-blockers, anticonvulsants, and CGRP antagonists. Lifestyle modifications include regular sleep, stress management, and avoiding triggers.', 'American Academy of Neurology Guidelines 2023', '1.0', ARRAY['migraine', 'headache', 'neurology', 'treatment', 'prevention'], ARRAY['acute therapy', 'preventive therapy', 'lifestyle', 'triggers']),
('Endocrinology', 'Type 2 Diabetes Management', 'Type 2 diabetes is characterized by insulin resistance and relative insulin deficiency. Treatment goals: HbA1c <7%, BP <130/80 mmHg, LDL <100 mg/dL. First-line therapy is metformin. Additional agents include sulfonylureas, DPP-4 inhibitors, GLP-1 agonists, and SGLT2 inhibitors. Regular monitoring of blood glucose, HbA1c, and complications screening is essential.', 'American Diabetes Association Standards of Care 2023', '1.0', ARRAY['diabetes', 'type 2', 'endocrinology', 'management', 'treatment'], ARRAY['glycemic control', 'complications', 'monitoring', 'lifestyle']),
('Psychiatry', 'Depression Treatment Guidelines', 'Major depressive disorder is characterized by depressed mood or loss of interest for ≥2 weeks. Treatment includes psychotherapy (CBT, IPT) and pharmacotherapy (SSRIs, SNRIs). First-line antidepressants: sertraline, escitalopram, fluoxetine. Treatment duration: 6-12 months after remission. Regular monitoring for suicidal ideation, especially in first 4 weeks. Referral to psychiatry for treatment-resistant cases.', 'American Psychiatric Association Guidelines 2023', '1.0', ARRAY['depression', 'psychiatry', 'treatment', 'antidepressants', 'psychotherapy'], ARRAY['medication', 'therapy', 'monitoring', 'suicide risk']),
('Rheumatology', 'Rheumatoid Arthritis Management', 'Rheumatoid arthritis is a chronic autoimmune inflammatory arthritis affecting small joints. Early diagnosis and aggressive treatment with DMARDs is crucial to prevent joint damage. First-line therapy: methotrexate. Additional agents: hydroxychloroquine, sulfasalazine, biologic DMARDs. Regular monitoring of disease activity, liver function, and bone density. Patient education on joint protection and exercise.', 'American College of Rheumatology Guidelines 2023', '1.0', ARRAY['rheumatoid arthritis', 'autoimmune', 'DMARDs', 'treatment', 'monitoring'], ARRAY['disease activity', 'joint damage', 'biologics', 'patient education'])
ON CONFLICT DO NOTHING;

-- Insert demo patient education materials
INSERT INTO patient_education (patient_id, topic, content, difficulty_level, language, created_at) VALUES
((SELECT id FROM patients WHERE email = 'alice.wilson@email.com'), 'Hypertension Management', 'Understanding your blood pressure: Normal BP is <120/80. Your target is <130/80. Lifestyle changes: Reduce salt intake, eat more fruits/vegetables, exercise regularly, maintain healthy weight, limit alcohol, quit smoking. Take medications as prescribed and monitor BP at home.', 'intermediate', 'English', '2024-09-10 10:00:00'),
((SELECT id FROM patients WHERE email = 'robert.chen@email.com'), 'Asthma Management', 'Asthma triggers: cold air, exercise, allergens, respiratory infections. Use your rescue inhaler before exercise. Keep a peak flow diary. Avoid smoking and secondhand smoke. Know your asthma action plan and when to seek emergency care.', 'intermediate', 'English', '2024-09-12 14:30:00'),
((SELECT id FROM patients WHERE email = 'maria.garcia@email.com'), 'Migraine Prevention', 'Common migraine triggers: stress, lack of sleep, certain foods, hormonal changes, bright lights, strong smells. Keep a headache diary to identify your triggers. Practice stress management techniques. Maintain regular sleep schedule. Take preventive medications as prescribed.', 'intermediate', 'English', '2024-09-11 09:15:00'),
((SELECT id FROM patients WHERE email = 'james.taylor@email.com'), 'Heart-Healthy Living', 'Cardiac diet: low sodium, low saturated fat, high fiber. Exercise: 150 minutes moderate activity weekly. Monitor weight, BP, and cholesterol. Take all medications as prescribed. Know warning signs of heart attack: chest pain, shortness of breath, arm/jaw pain.', 'intermediate', 'English', '2024-09-09 11:00:00'),
((SELECT id FROM patients WHERE email = 'jennifer.anderson@email.com'), 'PCOS Management', 'PCOS affects hormone balance and can cause irregular periods, acne, and weight gain. Treatment includes: healthy diet, regular exercise, weight management, medications for specific symptoms. Regular check-ups important for monitoring diabetes and heart disease risk.', 'intermediate', 'English', '2024-09-08 15:45:00')
ON CONFLICT DO NOTHING;

-- Add some sample medical scenarios for AI agent testing
INSERT INTO knowledge_base (category, title, content, source, version, keywords, related_topics) VALUES
('Emergency Medicine', 'Chest Pain Evaluation', 'Chest pain requires immediate evaluation. Red flags: sudden onset, severe pain, associated symptoms (shortness of breath, diaphoresis, nausea), radiation to arm/jaw, exertion-related. Immediate ECG and cardiac enzymes required. Consider STEMI, unstable angina, aortic dissection, pulmonary embolism. Time is critical for cardiac events.', 'Emergency Medicine Guidelines 2023', '1.0', ARRAY['chest pain', 'emergency', 'cardiac', 'evaluation', 'red flags'], ARRAY['ECG', 'cardiac enzymes', 'STEMI', 'aortic dissection']),
('Pediatrics', 'Fever in Children', 'Fever in children <3 months requires immediate evaluation. Age 3-36 months: evaluate based on appearance and behavior. >36 months: focus on symptoms and duration. Red flags: lethargy, poor feeding, rash, neck stiffness, difficulty breathing. Treatment: antipyretics for comfort, not to reduce fever. Hydration is crucial.', 'American Academy of Pediatrics Guidelines 2023', '1.0', ARRAY['fever', 'pediatrics', 'children', 'evaluation', 'red flags'], ARRAY['antipyretics', 'hydration', 'bacterial infection', 'viral infection']),
('Geriatrics', 'Polypharmacy Management', 'Polypharmacy (≥5 medications) increases risk of adverse drug events, drug interactions, and non-adherence. Regular medication review essential. Consider: deprescribing unnecessary medications, monitoring for side effects, simplifying regimens, using lowest effective doses. Involve patients in medication decisions.', 'American Geriatrics Society Guidelines 2023', '1.0', ARRAY['polypharmacy', 'geriatrics', 'medication', 'deprescribing', 'drug interactions'], ARRAY['medication review', 'adverse events', 'patient safety', 'adherence'])
ON CONFLICT DO NOTHING;

COMMIT;
